---
title: "HW1:Importing and Playing with Excel File in R"
author: "Qianyi Yu"
date: "2024-09-18"
output: html_document
---

# 
## 
### 
#### 1. Import csv data and adding header row

```{r}
Typical_Employee_Survey_Data <-read.csv("~/Desktop/RBS/Business Forcasting/Typical_Employee_Survey_Data.csv", header=FALSE)
colnames(Typical_Employee_Survey_Data) <- c("Employee_age", "Gender", "Job_satisfaction", "Work_life_balance", "Career_opportunity", "Manager_support", "Team_dynamics", "Compensation_satisfaction", "Remote_work_support", "Personal_development", "Work_engagement")
```
#
##
###
#### 2. 5-point summary and boxplot for each column

```{r}
#summary for each column
summary(Typical_Employee_Survey_Data)
```

```{r}
#boxplot for numerical columns
boxplot(Typical_Employee_Survey_Data$Career_opportunity)
```

#### 3. Convert the columns that need to be converted to Factors

```{r}
Typical_Employee_Survey_Data$Career_opportunity <- as.factor(Typical_Employee_Survey_Data$Career_opportunity)
```



#### 4. Plot right visual for each column

```{r}
boxplot(Typical_Employee_Survey_Data$Employee_age, main="Barplot for Employee_age")
hist(Typical_Employee_Survey_Data$Gender, main="Barplot for Gender")
hist(Typical_Employee_Survey_Data$Job_satisfaction, main="Barplot for Job_satisfaction")
hist(Typical_Employee_Survey_Data$Work_life_balance, main="Barplot for Work_life_balance")
boxplot(Typical_Employee_Survey_Data$Career_opportunity, main="Barplot for Career_opportunity")
hist(Typical_Employee_Survey_Data$Manager_support, main="Barplot for Manager_support")
hist(Typical_Employee_Survey_Data$Team_dynamics, main="Barplot for Team_dynamics")
hist(Typical_Employee_Survey_Data$Compensation_satisfaction, main="Barplot for Compensation_satisfaction")
hist(Typical_Employee_Survey_Data$Remote_work_support, main="Barplot for Remote_work_support")
hist(Typical_Employee_Survey_Data$Personal_development, main="Barplot for Personal_development")
hist(Typical_Employee_Survey_Data$Work_engagement, main="Barplot for Work_engagement")
```

#### 5. Plot scatter plots to show few relationships

```{r}
#plotting column Employee_age and Career_opportunity
plot(Typical_Employee_Survey_Data$Employee_age,Typical_Employee_Survey_Data$Career_opportunity,main = "Scatter Plot of Employee_age vs Career_opportunity",xlab = "Employee_age",ylab = "Career_opportunity",pch=19,col="blue")
```


```{r}
#plotting column Job_satisfaction and Manager_support
plot(Typical_Employee_Survey_Data$Gender, Typical_Employee_Survey_Data$Manager_support, main = "Scatter plot of Job_satisfaction vs Manager_support",xlab = "Manager_support", ylab = "Job_satisfaction", pch = 19, col= "green")
```


```{r}
#plotting multiple columns
pairs(Typical_Employee_Survey_Data[, c("Employee_age", "Career_opportunity", "Manager_support", "Job_satisfaction")], 
      main = "Scatter Plot Matrix",
      pch = 19, col = "red")
```

